### ISSUE TITLE
META - Metadata parser

### ISSUE THREAD

**Issue by cleaneddata** [ki2w/flux#7]
- [ ] Create specification
- [ ] Update TOML parser, add annotations(like @/annotation, which will be core respond to module functions)
- [ ] migrate all cratespec files to META
- [ ] migrate all plugins to META
- [ ] add version control system(will be in other PR)
- [ ] create centralized package manager
